"""create base tables

Revision ID: 185eb34411cc
Revises: 
Create Date: 2025-10-04 14:46:30.944994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185eb34411cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meshs',
    sa.Column('x_limit', sa.Integer(), nullable=False),
    sa.Column('y_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meshs_id'), 'meshs', ['id'], unique=True)
    op.create_table('probes',
    sa.Column('mesh_id', sa.UUID(), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=False),
    sa.Column('y_position', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mesh_id'], ['meshs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probes_id'), 'probes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_probes_id'), table_name='probes')
    op.drop_table('probes')
    op.drop_index(op.f('ix_meshs_id'), table_name='meshs')
    op.drop_table('meshs')
    # ### end Alembic commands ###
